print('\033[31;46mEXERCÍCIO 22\033[m')
print('\033[1;33;44m`´\033[m'*20)
print('\033[7mAnaLinador de nomes\033[m')
print('\033[33;44m`´\033[m'*20)
nome = str(input('\033[4mDigite seu nome completo:\033[m ')).strip()
print('Analizando seu nome...')
print('seu nome em letras maiuscula é {}'.format(nome.upper()))
print('seu nome em letras minusculas é {}'.format(nome.lower()))
print('seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
#print('seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('seu pimeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))